### ISSUE TITLE
Can Streamplify be used to produce k-permutations of n?

### ISSUE THREAD

**Issue by LeonidShamis** [beryx/streamplify#7]
Can Streamplify be used to produce k-permutations of n (https://en.wikipedia.org/wiki/Permutation#k-permutations_of_n)?

For instance:

P(n,r)=P(5,3)=5!(5−3)!= 60 (https://www.calculatorsoup.com/calculators/discretemathematics/permutations.php?n=5&r=3&action=solve)

Or for n = {Alice, Bob, Eve, Mallory} to produce P(4,2)=4!(4−2)!=12 results:
(Alice,   Bob)
(Alice,   Eve)
(Alice,   Mallory)
(Bob,     Alice)
(Bob,     Eve)
(Bob,     Mallory)
(Eve,     Alice)
(Eve,     Bob)
(Eve,     Mallory)
(Mallory, Alice)
(Mallory, Bob)
(Mallory, Eve)

Thank you.

**Comment by siordache** [comment]
Yes, it is possible. See [this example](https://github.com/beryx/streamplify/blob/master/streamplify-examples/src/main/java/org/beryx/streamplify/example/Arrangements.java).

**Comment by LeonidShamis** [comment]
Thank you for the prompt response.
This is indeed exactly what I was looking for.
I see that org.beryx.streamplify.permutation.Permutations already selects the right Permutations implementation depending on the permutation length, so I expect that it will support length greater than LongPermutations.MAX_LENGTH=20 but less then BigIntegerPermutations.MAX_LENGTH=20_000.
The example states
> However, for improved performance, you may provide implementations based on the
> org.beryx.streamplify.LongIndexedSpliterator and org.beryx.streamplify.BigIntegerIndexedSpliterator

Does it mean that there is another more efficient way of producing k-permutations of n that is different from this example and uses org.beryx.streamplify.LongIndexedSpliterator and org.beryx.streamplify.BigIntegerIndexedSpliterator? Is there an example for that anywhere?
Thank you.

**Comment by LeonidShamis** [comment]
I have tried it with small number of n & k and it worked fine. However when n is large it fails with "java.lang.OutOfMemoryError: Java heap space" and strangely is seems to be using org.beryx.streamplify.LongIndexedSpliterator and not BigIntegerIndexedSpliterator as I expected for n>20

I've added a sample repo [https://github.com/LeonidShamis/NamesPermutations](https://github.com/LeonidShamis/NamesPermutations) to demonstrate the issues.

In my program I get the (n) names from the input file and then produce k permutations of n names. I've tried with k=5 and 2 input files with 23 and 1700 names respectively.

When running with a smaller file (run.cmd 23_names.txt) it works, but when running with a larger file (run.cmd 1700_names.txt) it does not work even though I allocate really large heap:

...
...
k-permutations of n names from the input file 1700_names.txt
press any key to continue or Ctrl^C to exit...

Permutations on array length 1700

java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid10216.hprof ...
Heap dump file created [1314200336 bytes in 9.657 secs]
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
        at java.lang.StringBuilder.append(StringBuilder.java:136)
        at java.lang.StringBuilder.append(StringBuilder.java:76)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:457)
        at java.lang.StringBuilder.append(StringBuilder.java:166)
        at java.util.StringJoiner.add(StringJoiner.java:185)
        at java.util.stream.Collectors$$Lambda$5/933699219.accept(Unknown Source)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at org.beryx.streamplify.LongIndexedSpliterator.forEachRemaining(LongIndexedSpliterator.java:167)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
        at org.beryx.streamplify.LongIndexedSpliterator.forEachRemaining(LongIndexedSpliterator.java:167)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at permutations.ArrangementsStreamplify.main(ArrangementsStreamplify.java:72)

**Comment by siordache** [comment]
ArrangementsStreamplify(1700, 5) uses Permutations(5) and Combinations(1700, 5). In both cases a LongIndexedSpliterator can still do the job.
However, if you call ArrangementsStreamplify(1700, 6), you'll see in the stack trace that a BigIntegerIndexedSpliterator is needed for Combinations.
And if you call ArrangementsStreamplify(1700, 21), you'll see that a BigIntegerIndexedSpliterator is needed for both Permutations and Combinations.

The problem in your code is with the last _collect_ in the statement below, which tries to join all arrangements into a single String:

```
System.out.println(new ArrangementsStreamplify(namesArray.length, 5)
    .stream()have 
    .map(arr -> Arrays.stream(arr).mapToObj(i -> namesArray[i]).collect(Collectors.toList()).toString())
    .collect(Collectors.joining("\n")));
```

With 1700 names and k=5 you have 1700!/(1700−5)! arrangements, which is a 16-digit number.
By joining the representations of all these arrangements you end up with a string that exceeds your computer's memory.

The solution is to print each arrangement at the moment when it is retrieved from the stream.
(Streamplify doesn't store the stream elements in memory, it generates them one by one when needed.)

```
Stream<String> permStream = new ArrangementsStreamplify(namesArray.length, 5)
    .stream()
    .map(arr -> Arrays.stream(arr).mapToObj(i -> namesArray[i]).collect(Collectors.toList()).toString());
permStream.forEach(System.out::println);
```
Due to the huge number of arrangements, it will take extremely long to print all solutions, but the program should work with even much bigger lists of names,

Currently, there is no other another more efficient implementation for producing k-permutations of n.
An implementation based on the LongIndexedSpliterator and BigIntegerIndexedSpliterator implies coming up with efficient algorithms for the methods computeNext() and unrank(). I expect the unranking part to be quite tricky.  It's an interesting intellectual challenge, but for practical purposes the performance gain would probably be negligible.

**Comment by LeonidShamis** [comment]
Brilliant!
Hardly using any heap. I have also changed it slightly to use parallelStream() instead of stream() for multi-core parallel stream.
Great project - (many) Star(s) project.
Thank you so much!!
